"""Added User model

Revision ID: 5764f331cf5c
Revises: b2b050e656fa
Create Date: 2025-10-20 19:57:14.505082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5764f331cf5c'
down_revision = 'b2b050e656fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plant_id', sa.Integer(), nullable=False))
        batch_op.alter_column('water_level',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'plant', ['plant_id'], ['id'])
        batch_op.drop_column('environment_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('environment_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'environment', ['environment_id'], ['id'])
        batch_op.alter_column('water_level',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.drop_column('plant_id')

    # ### end Alembic commands ###
