"""plant

Revision ID: b2b050e656fa
Revises: af9ad0a6f141
Create Date: 2025-10-20 07:49:05.999579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2b050e656fa'
down_revision = 'af9ad0a6f141'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('plant_type', sa.String(length=50), nullable=True),
    sa.Column('environment_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('ideal_humidity', sa.Float(), nullable=True),
    sa.Column('last_watered', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['environment_id'], ['environment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('environment', schema=None) as batch_op:
        batch_op.drop_column('type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('environment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.VARCHAR(length=20), nullable=True))

    op.drop_table('plant')
    # ### end Alembic commands ###
