"""Added created_at column to Environment

Revision ID: d63ff7ce4d62
Revises: 
Create Date: 2025-10-20 20:12:43.987846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd63ff7ce4d62'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('environment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('environment', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
